### PR TITLE
[tinygraph-1] Possible improvements

### LINKED ISSUE #1: Possible improvements
Nice library! I have some suggestions:

- **Undefined behavior!** 🐛
  - [`type_store.cpp`](https://github.com/Azer0s/tinygraph/blob/master/type/type_store.cpp#L17): `type` is copied into the temporary `t`. `t` is then copied again when the constructor for `Type` is invoked, meaning that after `tinygraph_typestore_add` returns, `t` is destroyed and the `char *` key inserted into `types` becomes a dangling pointer. Consider inserting `type_obj->name.c_str()` instead, or...
- **consider using [`string_view`](https://en.cppreference.com/w/cpp/string/basic_string_view)** instead of raw character pointers or `string &`s (and specifying [`less<>`](https://en.cppreference.com/w/cpp/utility/functional/less_void) as your `map`s' comparators). This will allow you to accept both `string &`s and `char *`s due to `string_view`'s implicit constructors.
- **Avoid using `map`'s `operator[]` when retrieving values** ([`graph.cpp`](https://github.com/Azer0s/tinygraph/blob/master/data/graph.cpp#L26))
  - When no value is present, because `operator[]` has to return a `T &`, [one is default constructed and returned](https://stackoverflow.com/a/8801171/7366707). This means that the result of `this->vertices[from]` is either a valid `shared_ptr`, or an empty one, which will conveniently segfault(!) when it is used. Consider using `find` with a conditional instead.
- **Avoid using `new`**, instead...
- **consider using [`make_shared`](https://en.cppreference.com/w/cpp/memory/shared_ptr/make_shared)** (C++ core guidelines: [C.151](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c151-use-make_shared-to-construct-objects-owned-by-shared_ptrs)), which, unlike `shared_ptr(T())`, will properly handle exceptions thrown during object construction
- Avoid redundant moves
  - [`type_store.cpp`](https://github.com/Azer0s/tinygraph/blob/master/type/type_store.cpp#L17): `type` is passed by value. `t` is then copied again when the constructor for `Type` is invoked, meaning the move was essentially a no-op
  - [`type.cpp`](https://github.com/Azer0s/tinygraph/blob/master/data/type.cpp#L10)
  - [`vertex.cpp`](https://github.com/Azer0s/tinygraph/blob/master/data/vertex.cpp#L8)
  - [`vertex.cpp`](https://github.com/Azer0s/tinygraph/blob/master/data/vertex.cpp#L16)
- Consider using [member initializer lists](https://en.cppreference.com/w/cpp/language/initializer_list). This helps with the previous problem, so
   ```cpp
   Vertex::Vertex(std::string name, std::shared_ptr<Type> type) {
       this->name = std::move(name);
       this->type = std::move(type);
   }
   ```
   becomes
   ```cpp
   Vertex::Vertex(std::string name, std::shared_ptr<Type> type) : name(name), type(type) { }
   ```
- Avoid unnecessary copies ([`util.cpp`](https://github.com/Azer0s/tinygraph/blob/master/functions/util.cpp#L8))
- Consider using `static constexpr` constants instead of macros ([`test.cpp`](https://github.com/Azer0s/tinygraph/blob/master/test.cpp#L9)); avoid macros wherever possible
- Avoid accepting `shared_ptr`s by reference when the function takes ownership ([`graph.cpp`](https://github.com/Azer0s/tinygraph/blob/master/data/graph.cpp#L17), [`connections.cpp`](https://github.com/Azer0s/tinygraph/blob/master/functions/connections.cpp#L10)) (C++ core guidelines: [R.34](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r34-take-a-shared_ptrwidget-parameter-to-express-that-a-function-is-part-owner))
- Consider making use of [namespaces](https://en.cppreference.com/w/cpp/language/namespace), which were made to avoid `library_name_prefixes`
- Avoid relative include paths
- Consider defining aliases for commonly-used types. `std::shared_ptr<std::map<std::string, std::any>>` is really long.
- Consider using [`ostringstream`](https://en.cppreference.com/w/cpp/io/basic_ostringstream) for concatenating strings ([`graph.cpp`](https://github.com/Azer0s/tinygraph/blob/master/data/graph.cpp#L36))
- Avoid library globals; [this](https://github.com/Azer0s/tinygraph/blob/master/type/type_store.cpp#L10) should probably be contained in an object.

I could open a PR if you'd like, but I don't know if you'd rather look over this yourself.

### PR DESCRIPTION
**Pull request by Azer0s**
Closes #1

### CODE REVIEW

File: data/graph.cpp [hunk 1]
```diff
@@ -8,59 +8,63 @@
...
+    }
 
-std::string Graph::str() {
-    std::string res;
+    std::string Graph::str() {
+        std::string res;
 
-    for (const auto& v : this->vertices) {
-        res += v.first;
+        for (const auto& v : this->vertices) {
```
Comment (svby) [inline data/graph.cpp]: Generally when iterating maps you could use structured bindings for readability:

```cpp
for (const auto &[key, vertex] : this->vertices) { ... }
```

File: data/edge.cpp [hunk 2]
```diff
@@ -5,6 +5,8 @@
 #include "types.h"
 #include <utility>
 
-Edge::Edge(std::shared_ptr<Vertex> vertex) {
-    this->to = std::move(vertex);
+namespace tinygraph {
+    Edge::Edge(std::shared_ptr<Vertex> vertex) {
```
Comment (svby) [inline data/edge.cpp]: IMO member initializers might be better here (for constructors in general)

File: data/types.h [hunk 3]
```diff
@@ -12,28 +12,29 @@
...
+        std::vector<std::shared_ptr<Edge>> connections;
+        std::map<std::string, std::any> properties;
+    };
+
+    class Edge {
+    public:
+        explicit Edge(std::shared_ptr<Vertex>);
+
+        std::shared_ptr<Vertex> to;
+        std::shared_ptr<std::map<std::string, std::any>> properties;
```
Comment (svby) [inline data/types.h:36]: Is there a reason why the property map should be dynamically allocated?

File: data/types.h [hunk 4]
```diff
@@ -12,28 +12,29 @@
...
-
+namespace tinygraph {
+    class Edge;
+
+    class Vertex {
+    public:
+        Vertex(std::string, std::shared_ptr<Type>);
+        ~Vertex();
+
+        void add_prop(const char*, std::any);
```
Comment (svby) [inline data/types.h]: Missing parameter names in header (they aren't unused) throughout this file

File: functions/connections.cpp [hunk 5]
```diff
@@ -7,17 +7,23 @@
 #include <any>
 #include "../data/types.h"
 
-std::shared_ptr<std::map<std::string, std::any>> tinygraph_vertex_link(const std::shared_ptr<Vertex>& from, const std::shared_ptr<Vertex>& to, bool undirected) {
-    auto to_edge = std::shared_ptr<Edge>(new Edge(to));
-    to_edge->properties = std::shared_ptr<std::map<std::string, std::any>>(new std::map<std::string, std::any>);
-    from->connections.push_back(to_edge);
+#pragma clang diagnostic push
+#pragma ide diagnostic ignored "performance-unnecessary-value-param"
```
Comment (svby) [inline functions/connections.cpp]: Probably not a great idea to ignore warnings (*cough* rounding errors 😅), at least without a comment. I think for a warning like this the cause of the warning instead should be fixed.

I guess this might be because the shared pointer doesn't need to be copied since it gets copied after being forwarded to `make_shared`, so a `move` into `make_shared` might fix it(?)

Also, warning pragmas are of course not compiler-agnostic.

File: functions/util.cpp [hunk 6]
```diff
@@ -5,16 +5,18 @@
...
-        return std::any_cast<std::string>(val);
-    } else if (val.type() == typeid(float)) {
-        return std::to_string(std::any_cast<float>(val));
-    } else if (val.type() == typeid(const char*)) {
-        return std::any_cast<const char*>(val);
-    } else {
-        return "<value>";
+namespace tinygraph {
+    std::string any_to_str(const std::any* val) {
+        if (val->type() == typeid(int)) {
```
Comment (svby) [inline functions/util.cpp:11]: Use of `typeid` without including `<typeinfo>` makes the program ill-formed (yeah...).

I assume it was probably transitively included by `<any>` in this case, but standard headers (except for, I think, `<initializer_list>` and `<ios>` etc.) are not required to include any other headers, so one should generally try to explicitly include everything needed.

```shell
> grep "typeinfo" -nr -m1 -- /usr/include/c++/9.3.0/any
36:#include <typeinfo>
```

File: data/types.h (hunk 3 above)
Comment (Azer0s) [reply data/types.h:36]: Yes. When an edge is undirected, a property is valid for both A->B as well as B->A.

File: data/graph.cpp (hunk 1 above)
Comment (Azer0s) [reply data/graph.cpp]: Done

File: data/edge.cpp (hunk 2 above)
Comment (Azer0s) [reply data/edge.cpp]: Done

File: data/types.h (hunk 4 above)
Comment (Azer0s) [reply data/types.h]: Done

File: functions/connections.cpp (hunk 5 above)
Comment (Azer0s) [reply functions/connections.cpp]: Done, sort of (?)

File: functions/util.cpp (hunk 6 above)
Comment (Azer0s) [reply functions/util.cpp:11]: Done

**Comment by Azer0s** [comment]
@stuhlmeier Does this cover everything from your list?

File: functions/connections.cpp (hunk 5 above)
Comment (svby) [reply functions/connections.cpp]: I think that's probably fine, though if you don't want the move it should be alright to make `from` a const reference because it isn't necessarily copied in every code path.

**Comment by svby** [comment]
I think so. Considering that my issue was quite broad, things like introducing string views or using `map::find` probably belong in a separate feature request.

File: functions/connections.cpp (hunk 5 above)
Comment (Azer0s) [reply functions/connections.cpp]: Done
